### PR TITLE
Added Go to hook handlers integration tests

### PR DESCRIPTION
**Pull request by honzajavorek**
Let's see whether everything works together!

### CODE REVIEW

**Comment by honzajavorek** [comment]
Hmm, I think it won't pass, because there is no `npm install dredd -g` which could be replaced, in the https://github.com/snikch/goodman/blob/master/.travis.yml file.

**Comment by ddelnano** [comment]
@honzajavorek does it need to be installed globally?

**Comment by honzajavorek** [comment]
It's just that the testing script doesn't count with such setup, that's
all. It looks for "npm install dredd" in the Travis' file and attempts to
replace it with "npm install ./__dredd__/...", which is a folder where the
tested version of Dredd lives during the test.

In this case, we would probably have to also check for package.json and
somehow inject the tested Dredd installation there.

**Comment by ddelnano** [comment]
@honzajavorek I keep getting build errors on the `npm install` when it is trying to build protagonist.  Here is one of the failed [jobs](https://travis-ci.org/snikch/goodman/builds/141841600).  I originally was using whatever node version travis pre installs (something 0.10.x) but then tried using 5.11.x and still received the same failures.

**Comment by ddelnano** [comment]
@honzajavorek so I had another PR open on the goodman repo that I tried re running the build (it was failing for a different reason) and now it can't `npm install` either.  I looked at protagonist and saw they released a new version yesterday and that the current dredd package.json would have installed that version.

**Comment by honzajavorek** [comment]
@ddelnano Protagonist should install all right. There were some issues with the latest version on Mac, but they released a fix (1.4.1) immediately - https://github.com/apiaryio/protagonist/releases

From the build you linked it seems to me you need to turn Travis into a `sudo` mode, otherwise Protagonist will have hard time during installation, since there are probably some essential libs / build tools missing. See `dredd-example`'s minimal config: https://github.com/apiaryio/dredd-example/blob/master/.travis.yml

I didn't realise this before, but since Protagonist is Dredd's prominent dependency, we should probably mention this somewhere and test out again (and update) our Travis CI configs we have all over the docs :grimacing:

We soon plan to depend on js-only version of the parser by default though.

**Comment by ddelnano** [comment]
@honzajavorek I will try using sudo in the travis build but what is weird is how my other build worked previously and now it is failing on the install.

**Comment by ddelnano** [comment]
@honzajavorek I updated the build with `sudo: required` and it is still failing on installation, when 2 weeks ago when I was working on the PR it was working fine https://travis-ci.org/snikch/goodman/jobs/142013584 .

Here is the PR https://github.com/snikch/goodman/pull/8

**Comment by honzajavorek** [comment]
See https://github.com/snikch/goodman/pull/10. Just tested out on our hooks repos and it seems to work now.

**Comment by honzajavorek** [comment]
@ddelnano Thanks! That should do the trick for our testing script without any changes. Let's see how it goes.

**Comment by honzajavorek** [comment]
🎉 

https://travis-ci.org/apiaryio/dredd/builds/145563920

screen shot 2016-07-18 at 18 08 17

**Comment by ddelnano** [comment]
👏

**Pull request merged**
