### PR TITLE
Rename DreddCommand class to CLI

### PR DESCRIPTION
**Pull request by michalholasek**
#### :rocket: Why this change?
`DreddCommand` is really confusing name used for Dredd's command line interface - I think simply `CLI` is generally more clear in communicating what the class / abstraction does.

#### :white_check_mark: What didn't I forget?

- [ ] To write docs - N/A
- [ ] To write tests - N/A
- [x] To put [Conventional Changelog](https://dredd.readthedocs.io/en/latest/contributing/#sem-rel) prefixes in front of all my commits and run `npm run lint`

### CODE REVIEW

**Comment by honzajavorek** [comment]
Two comments:

### CLIInfo

I really don't like having `CLIInfo` as a name for a variable not holding a class. I know there are no good solutions when it starts with an abbreviation, but if I have to choose, I vote for `cliInfo` instead.

### cli-test.js

> test/integration/dredd-command-test.js → test/integration/cli-test.js

This makes it a bit confusing, because then there are several tests with the same names: `test/integration/cli-test.js` versus the whole `test/integration/cli/` directory, containing `test/integration/cli/cli-test.js` file. This should get resolved/renamed/restructured before merging.

**Comment by michalholasek** [comment]
@honzajavorek Addressed in https://github.com/apiaryio/dredd/pull/1054/commits/e22b00979d5f0de6ff98807fc0b795de9e804b83 and https://github.com/apiaryio/dredd/pull/1054/commits/409ae1727c6af7956ba75b94f60cf5cdbd76cb0b.

**Comment by honzajavorek** [comment]
One idea: what about

```
/ dredd
    / test
        / e2e
        / integration
        / unit
```

? We could have a `e2e` folder for tests running Dredd as a subprocess, and `integration` for anything else which is not a `unit` test.

**Comment by honzajavorek** [comment]
Oh, you're fast. Okay then.

**Comment by honzajavorek** [comment]
Filing separately, as an idea: https://github.com/apiaryio/dredd/issues/1072

**Pull request merged**
