### PR TITLE
Update dependencies that were effectively downgraded & remove some unused dependencies

### PR DESCRIPTION
**Pull request by realityking**
#### :rocket: Why this change?

In the move to fixed dependency versions (f0f200b) some dependencies were effectively downgraded as there was a newer, in-range, version at the time.

While looking at the dependencies, I also found some unused dev dependencies:
* `coffee-coverage` isn't used anymore after decaffeinating

Many more things that are outdated but this seem like obvious wins 🙂

#### :white_check_mark: What didn't I forget?

- [ ] To write docs
- [ ] To write tests
- [X] To put [Conventional Changelog](https://dredd.readthedocs.io/en/latest/contributing/#sem-rel) prefixes in front of all my commits and run `npm run lint`

### CODE REVIEW

**Comment by honzajavorek** [comment]
Thanks! This is definitely a good idea. It will take me some time to check licensing etc. of the packages, will track the progress here:

- [x] async@2.6.0
- [x] chai@4.1.2
- [x] cross-spawn@5.1.0
- [ ] glob@7.1.2
- [ ] js-yaml@3.10.0
- [ ] markdown-it@8.4.1
- [ ] proxyquire@1.8.0
- [ ] uuid@3.2.1
- [ ] which@1.3.0
- [ ] winston@2.4.0
- [ ] eslint-config-airbnb-base@11.3.0

**Comment by honzajavorek** [comment]
@realityking I think once the `eslint-config-airbnb-base` is sorted, we're good to go, but _without_ winston for now. With regard to #765 and the long-term intention to replace winston with something like [debug](https://github.com/visionmedia/debug) I'm honestly a bit lazy to proceed with the upgrade internally right now.

**Comment by realityking** [comment]
Thanks @honzajavorek! I pushed a new version without the bump for `winston`.

As for `eslint-config-airbnb-base`, that's already a dependency through `eslint-config-airbnb` but I'm happy to split this into another PR.

**Comment by honzajavorek** [comment]
> I'm happy to split this into another PR

Let's wait just a little bit, my hunch would be this one could get resolved in a timely manner. It's Airbnb, they could care about licensing 😄

**Comment by ljharb** [comment]
Note that the "license" field in package.json, which is SPDX-compliant, is *more* than sufficient, the actual LICENSE file is not required. (that said, I've merged https://github.com/airbnb/javascript/pull/1746)

**Comment by honzajavorek** [comment]
@ljharb Thanks! 👍 I answered to your comment under airbnb/javascript#1746.

**Comment by realityking** [comment]
Based on the above discussion I removed the `eslint-config-airbnb` since I assume you'll want to update to a version that includes the License file.

I'll open a separate PR to track that.

**Comment by ljharb** [comment]
With or without the license file, the dependency is MIT licensed; there should be no need to remove it.

**Comment by honzajavorek** [comment]
@realityking btw I'm sorry for the failing Windows builds, they got very flaky recently. I plan to focus on fixing them, but until that time I'll keep retrying the builds for you 😕

**Comment by realityking** [comment]
@honzajavorek Looks like this all passes now :)

**Comment by realityking** [comment]
@honzajavorek Would it be possible to release a new minor version that includes this PR? 🙂

**Comment by honzajavorek** [comment]
Ha, I haven't noticed it's classified as `chore:`. If it was `feat:` or `fix:`, it gets autoreleased. Hmm...

**Comment by realityking** [comment]
Ah, good to know. Now I wish I had made #979 a `fix:` - I was debating that 😆

**Comment by realityking** [comment]
I had another PR I wanted to make this week - let me do that now and I'll put it in as a fix :)

**Comment by honzajavorek** [comment]
Yeah, I think `fix` fits better. Maybe I can find time to do [upgrades on Dredd Transactions](https://github.com/apiaryio/dredd-transactions/pulls) and to release a new Dredd with those propagated.

**Comment by honzajavorek** [comment]
Decided not to block on DT, this resolves the issue: https://github.com/apiaryio/dredd/pull/980

**Pull request merged**
