### PR TITLE
chore: decaffinate more test scripts

### PR DESCRIPTION
**Pull request by realityking**
#### :rocket: Why this change?

Removing some more cofffeescript bits & pieces.

Main advantage is that eslint lints these new JS files while nothing was linting the coffeescript files.

#### :memo: Related issues and Pull Requests

This completes the work started in #992 

#### :white_check_mark: What didn't I forget?

- [ ] To write docs
- [ ] To write tests
- [X] To put [Conventional Changelog](https://dredd.readthedocs.io/en/latest/contributing/#sem-rel) prefixes in front of all my commits and run `npm run lint`

### CODE REVIEW

**Comment by realityking** [comment]
Why would it work on Linux but fail on Windows? 🤔

**Comment by honzajavorek** [comment]
I didnt see the failing test (on mobile phone), but let me guess it’s the flaky beast we are trying to tame for second time in https://github.com/apiaryio/dredd/pull/1069

**Comment by realityking** [comment]
I don't think that's it. There are actually 32 failures, by the looks of it in places I've touched in this PR.

**Comment by michalholasek** [comment]
I wonder if `coffee` is doing file path delimiter normalization (`\` vs. `/`). Might be worth it to try `path.normalize` or `path.join`.

**Comment by honzajavorek** [comment]
Hmm, interesting. Looking at the failures I can't exactly say what could happen. The code seems to be the same. I suspected some implicit returns missing, I couldn't spot something right away tho, or Windows not being able to find `node` in PATH. But from the last error it's obvious the server process got started, so `node` is fine.

**Comment by realityking** [comment]
A lot smaller in scope but at least the tests pass for what's in here :)

**Comment by michalholasek** [comment]
@realityking I am sorry for the delay, we've had quite a lot of other work on our plates. Thank you for the PR, it's great!

**Comment by realityking** [comment]
@michalholasek no worries, I know what it's like 🙂

**Pull request merged**
