### PR TITLE
Add ability to ignore tests.

### PR DESCRIPTION
**Pull request by nweber**
Add the 'inverse' of the "only" option; the ability to ignore tests by name.

### CODE REVIEW

**Comment by netmilk** [comment]
Hey @nweber,

Thanks for the contribution! I'd prefer to call this functionality `skip` to be consistent in naming with the rest of the project.

**Comment by nweber** [comment]
Makes sense.  I'll make that change..  I'll also check out the tests; I'm not sure why they're failing.  I'll take another shot at running them locally to see what's up.  I'll update the pull request when it's sorted out.

**Comment by nweber** [comment]
Adjusted naming.
Fixed the failing tests.
I have not added new unit tests yet.

**Comment by michalholasek** [comment]
I'm very sorry we were not able to get back to this. I need to close this as we're going to work on #705 first, which requires having no pending Pull Requests. Having said that, we plan to revamp whole CLI layer (along with transaction names / paths) in the future, so it is possible we will consider adding `--skip` functionality aswell.

Thank you for all the work you've put into this!

**Comment by michalholasek** [comment]
Tracking [issue](https://github.com/apiaryio/dredd/issues/930).

**Pull request closed without merging**
