### PR TITLE
Add Node 8, drop Node 4

### PR DESCRIPTION
**Pull request by honzajavorek**
#### :rocket: Why this change?

- Node 8 is the latest even production-ready version and we should be sure Dredd supports it correctly.
- Node 4 end of life is April 2018 and there is no reason in supporting it anymore.
- We should not rely on loose dependency versioning - because there's no guarantee the interface, license, etc. won't change in minor or patch version. Semantic versioning is a nice idea, but not everyone follows it. Let's turn on [Greenkeeper](https://greenkeeper.io/) for this repo and let's pin all dependencies. Also adding `package-lock.json` as that's the standard way to work with `npm@5` now.

#### :memo: Related issues and Pull Requests

- Closes https://github.com/apiaryio/dredd/issues/754
- https://github.com/apiaryio/pitboss/issues/13

#### :white_check_mark: What didn't I forget?

- [x] To write docs
- [x] To write tests
- [x] To put [Conventional Changelog](https://dredd.readthedocs.io/en/latest/contributing/#sem-rel) prefixes in front of all my commits and run `npm run lint`

### CODE REVIEW

**Comment by honzajavorek** [comment]
I suspect a0c49c6 to fix the original issue with sandboxed hooks, but to break a lot of other things 😞 I'll continue later with this.

**Comment by honzajavorek** [comment]
@michalholasek If you like the changes, leaving up to you whether you want to merge this now or cherry-pick the commits at the end of your decaff PR and merge those together when the thing is ready.

**Comment by michalholasek** [comment]
@honzajavorek I am ok with merging it before decaff branch is done, just one note - shouldn't we consider this a breaking change, since we are dropping Node 4 support?

**Comment by honzajavorek** [comment]
@michalholasek It is a breaking change:

image

**Pull request closed without merging**
