### PR TITLE
Exclude documentation files and directories from the test coverage

### PR DESCRIPTION
**Pull request by kuba-kubula**

### CODE REVIEW

**Comment by netmilk** [comment]
I'm not sure if this is an actual solution for the confusing message about decreasing coverage when editing Documentation. Coverage should be calculated from the annotated JS code and no Markdown files can be annotated. But it's nothing bad to exclude the documentation explicitly.

**Comment by kuba-kubula** [comment]
@netmilk so is it free to merge?

**Comment by honzajavorek** [comment]
@kuba-kubula Does it support something like `*.md`? Otherwise seems OK to me, but I am also unsure about how `coffeecoverage` treats this and whether it's going to help. Did you try it out?

**Comment by w-vi** [comment]
It didn't change the coverage at all, you can have a look

**Comment by netmilk** [comment]
I think it has no effect. Closing.

**Comment by kuba-kubula** [comment]
Unfortunately Coveralls is in READ-ONLY mode due to database Upgrade event today... :(

**Comment by netmilk** [comment]
@kuba-kubula Please elaborate, I'm affraid I don't understand what do you mean.

**Comment by honzajavorek** [comment]
@netmilk I think he is trying to make some actual changes in README to see whether they affect coverage with the new setting. However, he's unable to evaluate the attempt as Coveralls won't report back now.

**Comment by netmilk** [comment]
@kuba-kubula @honzajavorek I meant this:

> Unfortunately Coveralls is in READ-ONLY mode due to database Upgrade event today... :(

**Pull request closed without merging**
