### PR TITLE
feat: add integration for Rust hooks

### PR DESCRIPTION
**Pull request by hobofan**
Hey there! 👋 

I wrote a hooks-handler for Rust: https://github.com/hobofan/dredd-hooks-rust.

This PR adds all the additional parts on the Dredd side that make a hooks integration more pleasant to use, similar to the other languages. I closely followed the Go integration, so I hope I didn't miss anything. The only thing I know that is missing is the Rust logo in the README, which I hope is okay for now.

Looking forward to your feedback!

### CODE REVIEW

**Comment by honzajavorek** [comment]
This is amazing! @hobofan 👏 👏 👏 It will take me some time to go through the changes, but in advance, thanks for all the work! Don't worry about the image, we'll get a new one 😄

**Comment by honzajavorek** [comment]
Just to let you know, I'm on it, but I've got carried away by investigation of https://github.com/apiaryio/dredd/issues/834.

However, I already asked for the new image with Rust logo added :wink:

**Comment by hobofan** [comment]
> However, I already asked for the new image with Rust logo added 😉

Thanks! :)

**Comment by hobofan** [comment]
Not yet. After opening this PR, the first thing I did was integrating the dredd hooks template test suite, but I haven't set up Travis for it yet. Will do so ASAP.

**Comment by hobofan** [comment]
@honzajavorek 
I added Travis CI with the test harness in https://github.com/hobofan/dredd-hooks-rust/pull/6.

**Comment by honzajavorek** [comment]
@hobofan awesome! 🎉

**Comment by hobofan** [comment]
🎉  Yay! Thanks @honzajavorek and @tjerabek for the smooth process! :)

**Comment by honzajavorek** [comment]
@hobofan I think you deserve all the praise, for contributing the Rust hooks 😄 It's so great. Thanks very much 👍

**Comment by honzajavorek** [comment]
Just an update, this didn't get released yet, because of https://github.com/apiaryio/dredd/pull/854, but the docs are built and up to date, so Dredd now features the how-to and Rust logo.

**Comment by hobofan** [comment]
I'm not in a rush ;)

**Comment by honzajavorek** [comment]
Finally. [v4.2.0](https://github.com/apiaryio/dredd/releases)!

**Pull request merged**
