### PR TITLE
Update hooks-go.md

### PR DESCRIPTION
**Pull request by m00sey**
#### :rocket: Why this change?
Examples fail to compile.

#### :white_check_mark: What didn't I forget?

- [ ] To write docs
- [ ] To write tests
- [ ] To put [Conventional Changelog](https://dredd.readthedocs.io/en/latest/contributing/#sem-rel) prefixes in front of all my commits and run `npm run lint`

### CODE REVIEW

**Comment by IngmarStein** [comment]
The goodman documentation was updated for https://github.com/snikch/goodman/releases/tag/0.2.1 but not here, sorry about that.

**Comment by m00sey** [comment]
Ah I see, that documentation seems a bit clearer too.

You can close this, or link to the other docs, up to you.

Thanks,

**Comment by ddelnano** [comment]
Its probably good to have it in both since the other languages have similar docs but I agree it needs to be thought of when any of the hook servers are updated.

**Comment by honzajavorek** [comment]
@m00sey Thanks for the change! Could you please just edit the commit messages so they're prefixed with `docs: `? Dredd uses Semantic Release, which needs these tags to know whether it should automatically release a new version or not when PR gets merged.

**Comment by honzajavorek** [comment]
@m00sey To me the commits still don't seem to be completely right, but I sense some fighting with git complexity here and I'm here to help - https://github.com/apiaryio/dredd/pull/824 It just took me a bit longer then I anticipated, I'm sorry for that. Thanks for the change!

@ddelnano Would you have any ideas on how we could easily sync the docs? Now that #728 is fixed by #775, almost anything is possible 😎

**Pull request closed without merging**
