### PR TITLE
chore: update inquirer to version 3.3.0

### LINKED ISSUE #768: Upgrade inquirer
The `inquirer` library drives the `dredd init` interactive initialization wizard and AFAIK that part of Dredd is undertested, so it needs manual verifying if changed. Also it's major version number change, so breaking changes can be expected when upgrading.

It would be nice if tests for the `dredd init` are added before upgrading.

### PR DESCRIPTION
**Pull request by realityking**
#### :rocket: Why this change?

The old `inquirer` version pulls down a lot of old dependencies and prevents deduplication.

#### :memo: Related issues and Pull Requests

Fixes #768

#### :white_check_mark: What didn't I forget?

Tested `dread init` manually with a couple of variations, everything works fine.

- [X] To write docs - N/A
- [X] To write tests - N/A
- [X] To put [Conventional Changelog](https://dredd.readthedocs.io/en/latest/contributing/#sem-rel) prefixes in front of all my commits and run `npm run lint`

### CODE REVIEW

**Comment by realityking** [comment]
As far as I can tell the failure is not directly related to `inquirer`. Any guess why it fails?

**Comment by honzajavorek** [comment]
@realityking Thanks for the PR! 🚀 I'm sorry for the delay in response - there has been some vacations on our end.

The problem with `inquirer` is that we do not have much tests for the interactive config logic. If you [check the coverage](https://coveralls.io/github/apiaryio/dredd), you can see even if tests were passing, it gives us little confidence to approve the upgrade:

image

So either the logic needs to be tried out manually to be sure nothing got broken (especially given the upgrade is 2 major and 2 minor versions) or we need to test it. Any help with that would be much appreciated.

-----

The tests are indeed failing for a different reason. It's probably related to failing master in Dredd Transactions - https://github.com/apiaryio/dredd-transactions/pull/108#issuecomment-337252277 Special Judicial Squad member @michalholasek is on his mission to figure it out.

**Comment by michalholasek** [comment]
Hello @realityking , we solved the issue with failing Swagger test https://github.com/apiaryio/dredd/issues/892 - could please rebase on top of current master to see if the tests pass? Thank you.

**Comment by realityking** [comment]
Saw the issue being closed :) I’m traveling right now, I’ll rebase ASAP.

**Comment by realityking** [comment]
@michalholasek @honzajavorek Rebased and tests pass.

I did run through the interactive mode a couple of times, choosing different options. I can't claim that this was comprehensive as I don't know all the option that there are. If you want some more through testing I'll have to take a look at the code and see what paths I might have missed.

**Comment by honzajavorek** [comment]
@realityking I think it shouldn't be hard to go through it. It is isolated in the [interactive-config.coffee](https://github.com/apiaryio/dredd/blob/master/src/interactive-config.coffee) file, and I can see only a couple of things to pay attention to:

- Check the Inquirer's interface - `inquirer.prompt(questions).then(callback)` But since you tried it out and it worked, I guess that's okay.
- Look at the `when:` functions and see whether they need any changes.

I didn't check the Inquirer's roadmap so I don't know if the breaking changes were due to dropping old Node support or whether they were actually changing something important. If you confirm you gave it a scan and you think it's all right, I'll merge this 👍

**Comment by realityking** [comment]
Good point on actually checking the changelog 😆 

Here's the changelog for 2.0

- Answer `name` with `.` are now expand in the answer object. e.g. `name.sub` would generate an answer object formatted as `{name: {sub: 'answer'}}`.
- `expand` prompt default value if not specified is now `help`.
- Drop support for node 0.10 and 0.12

and the one for 3.0

- Drop support for Node < 4
- Allow failing async validation by rejecting the returned Promise
- Fix bug with bottom bar

The node requirements are obviously harmless and `expand` is not used. I think we're safe (unless there are bugs 😉)

**Comment by honzajavorek** [comment]
Thanks! All looks good! Except for

> Drop support for Node < 4

Dredd still supports Node 4. We plan to support it until its maintenance end on 2018-04-01. However, it seems they dropped the support only because of their own maintenance convenience, not because they actually write code incompatible with Node 4. I'm willing to risk it. If it stops working, we can always pin/downgrade the version.

**Comment by honzajavorek** [comment]
And looking into the CI config, the Node 4 version is even [still there](https://github.com/SBoudrias/Inquirer.js/blob/master/.travis.yml#L4) 🙂

**Comment by realityking** [comment]
I think you missed the `<` in 

> Drop support for Node < 4

But yeah, the changelog doesn't make much sense 😄

**Comment by honzajavorek** [comment]
!!! You are right 😄

**Pull request merged**
