### PR TITLE
Keep forward slashes in URL if they're present

### LINKED ISSUE #93: Forward slashes are not added
Having blueprint:
## Address Detail [/account/addresses/{id}/]
- Parameters
  - id (required, string, `123`) ... String `id` of a customer address.

But dredd is making following request (verified by server side):
/account/addresses/123
instead of
/account/addresses/123/

On log trace it shows:
fail: GET /account/addresses/123/ duration: 176ms

So that is 404 as url doesn't match, and as a solution if I enable redirect to forward slashes, then it claims for 301 and still fails.

Thank you

### PR DESCRIPTION
**Pull request by coagulant**
Fixes #93
Adds micro-dependency (url-join)

### CODE REVIEW

**Comment by honzajavorek** [comment]
@coagulant I'm sorry we didn't get to this for so long :disappointed_relieved: Do you think you could try to rebase this against current master and revisit this PR?

**Comment by coagulant** [comment]
@honzajavorek sorry, but no, not using dredd anymore

**Comment by honzajavorek** [comment]
@coagulant OK, thanks for letting me know! I'll try to use your code anyway if applicable, thanks very much for the contribution!

**Comment by honzajavorek** [comment]
Closing this, replaced by #662 and released in v2.2.4. @coagulant Thank you for contributing, even though this PR didn't make it to `master`. You still inspired others to contribute this and finally, it's fixed! And I'm sorry it took such a long time.

**Pull request closed without merging**
