### PR TITLE
Delete ApiaryReporter.md

### PR DESCRIPTION
**Pull request by honzajavorek**
I don't know what this file is about, but I believe it's out of sync with any kind of reality for a long time and doesn't describe anything which would be used anywhere in Dredd or Apiary.

@w-vi @netmilk @kuba-kubula Could you please confirm my speculation (by merging this)?

### CODE REVIEW

**Comment by w-vi** [comment]
I don't know but apiary reporter still exists and the settings are still the same aren't they? Is this information described somewhere else?

**Comment by honzajavorek** [comment]
@w-vi There's [ApiaryReportingApi.md](https://github.com/apiaryio/dredd/blob/master/ApiaryReportingApi.md).

**Comment by w-vi** [comment]
@honzajavorek that is API Blueprint of the apiary reporter not the client side settings.

**Comment by honzajavorek** [comment]
@w-vi I see. Then I think this should live in the Dredd Documentation as it has nothing to do with the actual API, it's about usage of Dredd's Apiary reporter.

**Comment by w-vi** [comment]
@honzajavorek  :+1:

**Comment by honzajavorek** [comment]
Closing in favor of #464.

**Pull request closed without merging**
