### PR TITLE
v1.1.0 pre.4

### PR DESCRIPTION
**Pull request by honzajavorek**
Adressing #502 and #500.

### CODE REVIEW

**Comment by pksunkara** [comment]
CI is failing.

**Comment by pksunkara** [comment]
And also, you should probably use fury-adapter-swagger@0.8.0-pre.8

**Comment by honzajavorek** [comment]
CI just timeouted when waiting for dependent builds (#374), let's just wait and manually check if [all the individual branches](https://github.com/apiaryio/dredd/branches/active) pass, then we can merge and publish.

To use `fury-adapter-swagger@0.8.0-pre.8` I'd have to put it to `dredd-transactions` first, so next time. Let's treat this release just as the CS bug fix.

**Comment by honzajavorek** [comment]
Everything is passing. Will you merge?

screen shot 2016-06-01 at 13 46 24

**Pull request merged**
