### PR TITLE
Development dependency promoted, fixes last release

### PR DESCRIPTION
**Pull request by honzajavorek**
Dredd version 2.2.0 cannot be installed due to this 😞 Thanks very much @XVincentX for discovering this right away! 💕 👍 🇮🇹

### CODE REVIEW

**Comment by w-vi** [comment]
This has ruined my CI run , switching to stable :)

**Comment by honzajavorek** [comment]
@w-vi That won't help, stable is only avoiding pre-releases 😐 I'm really not sure how to catch these kinds of errors in CI before releasing the package.

**Comment by w-vi** [comment]
@honzajavorek maybe after publishing you can have a special CI run which would install dredd and run it, so at least you can catch it fast.

**Comment by honzajavorek** [comment]
@w-vi I have @XVincentX for that. I need something before release. Filing an issue: https://github.com/apiaryio/dredd/issues/642

**Comment by w-vi** [comment]
@honzajavorek what about build local package and then trying installing that? `rm -rf`ing node_modules so it starts clean?

**Pull request merged**
