### PR TITLE
Use protagonist instead of drafter

### PR DESCRIPTION
**Pull request by ascripcaru**
Also updated the dependencies

### CODE REVIEW

**Comment by ascripcaru** [comment]
can someone restart travis for node 0.12 ?

**Comment by w-vi** [comment]
@ascripcaru Wicked! Nice job! Thanks a lot. the node 0.12 seems to either have flaky test or there is something wrong .... restarting the build one more time if it fails then it needs investigation.

**Comment by ascripcaru** [comment]
@w-vi i have node v0.12.9 on my machine and all is green. I really don't know what is the problem. If this fails again I'll try to take change my node version and try again

**Comment by ascripcaru** [comment]
@w-vi all is green now

**Comment by w-vi** [comment]
@ascripcaru possibly flaky test then ... good news, cheers.

**Pull request merged**
