### PR TITLE
Fix enum URI parameters, fix Swagger with auth & multi responses

### PR DESCRIPTION
**Pull request by honzajavorek**
#### :rocket: Why this change?

The latest version of Dredd Transaction fixes recent regression bugs.

#### :memo: Related issues and Pull Requests

Closes https://github.com/apiaryio/dredd/issues/872
Closes https://github.com/apiaryio/dredd/issues/870

#### :white_check_mark: What didn't I forget?

- [ ] To write docs - N/A
- [x] To write tests (both regressions are now thoroughly tested in Dredd Transactions)
- [x] To put [Conventional Changelog](https://dredd.readthedocs.io/en/latest/contributing/#sem-rel) prefixes in front of all my commits and run `npm run lint`

### CODE REVIEW

**Comment by honzajavorek** [comment]
alt

**Comment by iamharish** [comment]
Cool. Eagerly waiting for this. When can we expect a release?

**Comment by kylef** [comment]
@iamharish I believe this was released 2 days ago when the PR was merged: https://github.com/apiaryio/dredd/releases/tag/v4.3.1

**Comment by iamharish** [comment]
I did upgrade to 4.4.0 but tests were still failing. Checked logs and seems like it's due to a different error now. Shall I file a new issue?

error: RangeError: Maximum call stack size exceeded
    at emitThree (events.js:140:20)
    at EventEmitter.emit (events.js:216:7)
    at TransactionRunner.emitError (/Users/hgokavarapu/.toolbox/homebrew/lib/node_modules/dredd/lib/transaction-runner.js:470:32)
    at TransactionRunner.emitHookError (/Users/hgokavarapu/.toolbox/homebrew/lib/node_modules/dredd/lib/transaction-runner.js:202:17)
    at /Users/hgokavarapu/.toolbox/homebrew/lib/node_modules/dredd/lib/transaction-runner.js:181:21
    at /Users/hgokavarapu/.toolbox/homebrew/lib/node_modules/dredd/node_modules/async/dist/async.js:1069:9
    at replenish (/Users/hgokavarapu/.toolbox/homebrew/lib/node_modules/dredd/node_modules/async/dist/async.js:946:17)
    at /Users/hgokavarapu/.toolbox/homebrew/lib/node_modules/dredd/node_modules/async/dist/async.js:950:9
    at _asyncMap (/Users/hgokavarapu/.toolbox/homebrew/lib/node_modules/dredd/node_modules/async/dist/async.js:1067:5)
    at /Users/hgokavarapu/.toolbox/homebrew/lib/node_modules/dredd/node_modules/async/dist/async.js:1153:16
    at timeLimit (/Users/hgokavarapu/.toolbox/homebrew/lib/node_modules/dredd/node_modules/async/dist/async.js:4970:5)
    at Object.timesSeries (/Users/hgokavarapu/.toolbox/homebrew/lib/node_modules/dredd/node_modules/async/dist/async.js:980:16)
    at TransactionRunner.runHooksForData (/Users/hgokavarapu/.toolbox/homebrew/lib/node_modules/dredd/lib/transaction-runner.js:187:20)
    at /Users/hgokavarapu/.toolbox/homebrew/lib/node_modules/dredd/lib/transaction-runner.js:96:24
    at /Users/hgokavarapu/.toolbox/homebrew/lib/node_modules/dredd/node_modules/async/dist/async.js:1069:9
    at replenish (/Users/hgokavarapu/.toolbox/homebrew/lib/node_modules/dredd/node_modules/async/dist/async.js:946:17)
    at iterateeCallback (/Users/hgokavarapu/.toolbox/homebrew/lib/node_modules/dredd/node_modules/async/dist/async.js:931:17)
    at /Users/hgokavarapu/.toolbox/homebrew/lib/node_modules/dredd/node_modules/async/dist/async.js:906:16
    at /Users/hgokavarapu/.toolbox/homebrew/lib/node_modules/dredd/node_modules/async/dist/async.js:1071:13
    at TransactionRunner.emitResult (/Users/hgokavarapu/.toolbox/homebrew/lib/node_modules/dredd/lib/transaction-runner.js:450:14)

**Comment by honzajavorek** [comment]
@iamharish Yes please, this looks like a different issue. Please try to cut down a minimal example consistently reproducing the error - from the traceback I'm unable to see what could be the problem. Thanks!

**Pull request merged**
