### PR TITLE
Added dredd-hooks-php to documentation 

### PR DESCRIPTION
**Pull request by ddelnano**
I have a working implementation of dredd hooks in PHP at this [repository](https://github.com/ddelnano/dredd-hooks-php).  I added it to the Dredd documentation so others can be aware of it, now that it is a stable release.

### CODE REVIEW

**Comment by ddelnano** [comment]
Please let me know if there is anything I can help with to expedite this.  Being my first open source contribution, I am very excited to have this merged in.

**Comment by netmilk** [comment]
Hi @ddelnano, it's absolutely super awesome, I'm just waiting for the graphics, because I want PHP logo to be part of the banner in the readme. I'll let you know soon!

**Comment by netmilk** [comment]
@ddelnano And that Lavarel example? Very lovely... 😻

**Comment by ddelnano** [comment]
Hey @netmilk.  Thanks for getting back to me.  Sounds awesome.  Haha thanks.  Yea I want to have some kind of framework agnostic (something really simple like how sinatra could be done in a single file) for people that don't have Laravel or framework X experience.  The idea being that any reasonably experienced php dev no matter their framework experience can wrap their head around the example.

**Comment by ddelnano** [comment]
Also if I wanted to propose a feature for the dredd-hooks implementations what is the best way of doing that before actually spending time implementing??  A Github issue?

**Comment by netmilk** [comment]
@ddelnano I think the best way how to propose a feature for dredd hooks for all languages is to rise an issue here in Dredd repo. It would be nice to keep discussion related to all languages and implementations here. :)

**Comment by netmilk** [comment]
@ddelnano Once again many thanks for you contribution! Send me your address and size to adam@apiary.io and I'll send you one of these:

img_7319

**Comment by ddelnano** [comment]
Just did.  This is awesome!

**Pull request merged**
