### PR TITLE
fix: Hook files are not always executed in alphabetical order (#890)

### PR DESCRIPTION
**Pull request by matthewl-biomatters**
Just a simple mistake with the compare function.

I'm not sure if adding extra hook files for testing is actually helpful?  On my machine they are the smallest number of files needed to trigger the bug but now the bug is fixed they are kind of messy.

### CODE REVIEW

**Comment by matthewl-biomatters** [comment]
The test failure seems unrelated so created as #892

**Comment by honzajavorek** [comment]
Thanks very much for the PR! 👍 🚀 I'm sorry for the delay in response - there has been some vacations on our end. @michalholasek has been implementing this recently, so he'll take care of the review.

**Comment by michalholasek** [comment]
Hello @matthewl-biomatters, we solved the issue with failing Swagger test you filed in https://github.com/apiaryio/dredd/issues/892 - could please rebase on top of current master to see if the tests pass? Thank you.

**Comment by michalholasek** [comment]
I looked into the failing test and it seems to be related to `./test/fixtures/sandboxed-hook*.js` glob pattern resolving to `sandboxed-hook.js` and `sandboxed-hooks-log.js` files, but I am not sure why it is causing the timeout. When I delete the glob pattern and replace previously used `sandbox-hook*.js`files with for example `/foo/bar/hook1.js` and `/foo/bar/hook2.js` (non existent files), it passes 🤔 

@matthewl-biomatters, would you be willing to dig deeper and resolve the issue?

**Comment by matthewl-biomatters** [comment]
Thanks @michalholasek I figured it was something like that but ran out of time yesterday.  Sorry I don't really have time to dig into it further but wonder if we could do this instead to avoid the risk of unrelated files that are add in future also weirdly breaking the tests.

`hookfiles: ['./**/*_hooks.*', '/baz/x.js', '/foo/y.js', '/bar/z.js', '/foo/a.js', '/bar/b.js', '/baz/c.js', '/foo/o.js', '/bar/p.js']`

**Comment by michalholasek** [comment]
@matthewl-biomatters Agree, please modify the test file and squash all commits into one. Thank you.

**Pull request merged**
