### PR TITLE
New hooks: `beforeValidation` and `beforeEachValidation`. Fixes #221

### LINKED ISSUE #221: Support for before validation hooks
Some [workarounds and tricks](https://github.com/apiaryio/dredd/issues/194#issuecomment-112436147) needs the server response to be modified before the validation. It would be nice to extend the hooks interface with `beforeValidation` and `beforeEachValidation` methods and these hooks should be performed after "Receive HTTP response" and before "Run Gavel validation" steps of the [Dredd execution lifecycle](https://dredd.readthedocs.org/en/latest/usage/#dredd-execution-lifecycle).

### PR DESCRIPTION
**Pull request by nevir**
These hooks fire after Dredd has received a response from the server, but before it is handed off to gavel. If you need to make modifications to the response before validation, these are the hooks for you.

### CODE REVIEW

**Comment by netmilk** [comment]
Hey @nevir! Great job! Thank you very much. I extended your work in #224 with some test to don't drop coverage and with some little documentation. Once it will be merged I'll close this PR and do a release immediately and let you know.

**Comment by nevir** [comment]
Sweet :)

**Comment by netmilk** [comment]
@nevir Just letting know that support for `beforeValidation` and `beforeEachValidation` was released yesterday in Dredd 0.6.1. Thanks again for great contribution!

**Comment by nevir** [comment]
Sweet! Thanks :)

**Pull request merged**
