### PR TITLE
Use Read the Docs

### PR DESCRIPTION
**Pull request by smizell**
This is the initial commit for using read the docs. 

http://dredd.readthedocs.org/en/latest/

Once this looks good, I'll work on cleaning them up and making it look correct on RTD.

### CODE REVIEW

**Comment by smizell** [comment]
@netmilk Here we go. This is kind of the first run in my opinion. It would be good to have @DeeStrong read over this and make sure it looks good. We can do all that editing in another PR or do it here.

**Comment by netmilk** [comment]
@smizell , would you mind adding brief manual how to install & run MKdocs locally?

**Comment by smizell** [comment]
@netmilk Great idea. I will put it in the README.

**Comment by smizell** [comment]
@netmilk This has done with commits squashed.

**Comment by smizell** [comment]
BTW, I simply linked to the installation instructions for MkDocs so you don't have to keep the instructions in sync.

**Pull request merged**
