### PR TITLE
Adds Prettier

### PR DESCRIPTION
**Pull request by artem-zakharchenko**
#### :rocket: Why this change?

- Automatic code formatting allows to focus on writing code, not maintaining semicolons, tabs, spacing, and other opinionated code format rules;
- Prettier provides consistent codebase-wide formatting of code. When integrated into Git hooks, or CI workflow, it makes your entire source code beautiful by default;
- When it can be automated it must be automated;

#### :memo: Related issues and Pull Requests

- Indirectly related to #1524 

#### :white_check_mark: What didn't I forget?

> Current Pull request introduces no changes to Dredd's logic. It only contains re-formatting of existing source code and test suites.

- [x] To write docs
- [x] To write tests
- [x] To put [Conventional Changelog](https://dredd.org/en/latest/internals.html#sem-rel) prefixes in front of all my commits and run `npm run lint`
- [x] To format existing source code
- [x] To format existing tests
- [x] To integrate Prettier with Git hooks/CI pipeline
- [x] Set `format-check` job as optional in the repository settings

### CODE REVIEW

**Comment by artem-zakharchenko** [comment]
Experiencing flaky tests on CI and on local (both feature branch and master):

* `childProcess-test`
* `HooksWorkerClient-test`

No specific assertion steps to highlight, random steps seems to fail.

**Comment by artem-zakharchenko** [comment]
I usually use `lint-staged` + `prettier` on `pre-commit` Git hook to make sure only staged chunks are formatted. It's also fine to discuss another approach to automate code formatting as a part of build/CI, as not everybody may use in-IDE auto-formatting (and not every IDE may use Prettier, even if its config is found).

**Comment by honzajavorek** [comment]
I've rebased the PR so you don't need to wait for AppVeyor in the morning. (I'm sorry for an unsolicited force push to your branch.)

**Comment by honzajavorek** [comment]
The new check seems to work 😏 

```
> prettier --check 'lib/**/*.js' 'test/**/*.js'

Checking formatting...
lib/addHooks.js
lib/annotationToLoggerInfo.js
lib/childProcess.js
lib/CLI.js
lib/compileTransactionName.js
lib/configureReporters.js
lib/configUtils.js
lib/Dredd.js
lib/getGoBinary.js
lib/getProxySettings.js
lib/hooksLog.js
lib/HooksWorkerClient.js
lib/init.js
lib/logger.js
lib/performRequest.js
lib/prettifyResponse.js
lib/readLocation.js
lib/resolveLocations.js
lib/resolveModule.js
lib/resolvePaths.js
lib/sortTransactions.js
lib/TransactionRunner.js
test/.eslintrc.js
test/fixtures/blog/app.js
test/fixtures/blog/hooks.openapi2.js
test/fixtures/request/application-octet-stream-hooks.js
test/fixtures/sanitation/any-content-guard-pattern-matching.js
test/fixtures/sanitation/any-content-pattern-matching.js
test/fixtures/sanitation/plain-text-response-body.js
test/fixtures/sanitation/response-body-attribute.js
test/fixtures/sanitation/response-headers.js
test/fixtures/sanitation/uri-parameters.js
test/integration/cli/api-blueprint-cli-test.js
test/integration/cli/api-description-cli-test.js
test/integration/cli/configuration-cli-test.js
test/integration/cli/hookfiles-cli-test.js
test/integration/cli/openapi2-cli-test.js
test/integration/cli/reporters-cli-test.js
test/integration/cli/server-process-cli-test.js
test/integration/configuration/resolveConfig-test.js
test/integration/regressions/regression-152-test.js
test/integration/regressions/regression-319-354-test.js
test/integration/regressions/regression-615-test.js
test/integration/regressions/regression-893-897-test.js
test/unit/configuration/normalizeConfig-test.js
test/unit/init/applyAnswers-test.js
test/unit/init/detectApiDescription-test.js
test/unit/init/detectCI-test.js
test/unit/init/detectLanguage-test.js
test/unit/init/detectServer-test.js
test/unit/init/printClosingMessage-test.js
test/unit/init/updateAppVeyor-test.js
test/unit/init/updateCircleCI-test.js
test/unit/init/updateTravisCI-test.js
test/unit/init/updateWercker-test.js
test/unit/performRequest/createTransactionResponse-test.js
test/unit/performRequest/detectBodyEncoding-test.js
test/unit/performRequest/getBodyAsBuffer-test.js
test/unit/performRequest/normalizeBodyEncoding-test.js
test/unit/performRequest/normalizeContentLengthHeader-test.js
test/unit/performRequest/performRequest-test.js
test/unit/reporters/ApiaryReporter-test.js
test/unit/reporters/BaseReporter-test.js
test/unit/reporters/CLIReporter-test.js
test/unit/reporters/DotReporter-test.js
test/unit/reporters/HTMLReporter-test.js
test/unit/reporters/MarkdownReporter-test.js
test/unit/reporters/NyanReporter-test.js
test/unit/reporters/XUnitReporter-test.js
Code style issues found in the above file(s). Forgot to run Prettier?
```

**Comment by artem-zakharchenko** [comment]
Thank you, @honzajavorek. Proceeding with formatting.

**Comment by artem-zakharchenko** [comment]
Current CI fails on the broken link to "cucumber.io" docs:

```
Warning, treated as error:
/home/circleci/project/docs/hooks/index.rst.rst:10:broken link: https://cucumber.io/docs/cucumber/api/#hooks (Anchor 'hooks' not found)
```

Investigating, but should be fixed in a separate Pull request, does not relate to the introduced changes.

**Comment by artem-zakharchenko** [comment]
@honzajavorek, could you please review? CI looks okay, apart from the Cucumber link in the docs. Thanks.

**Comment by artem-zakharchenko** [comment]
Cucumber docs are running, restarting CI workflow...

**Pull request merged**
