### PR TITLE
Add support for hiding sensitive headers in reports.

### PR DESCRIPTION
**Pull request by realityking**
This is an implementation for #421.

This is very much WIP. Stuff do to includes:

* [ ] Write tests
* [ ] Apiary reporter doesn't censor tests

I'd appreciate it if somebody could look over the code I do have and some help/guidance on the open tasks.

### CODE REVIEW

**Comment by honzajavorek** [comment]
@realityking Thanks very much! We'll take a look at it with @netmilk and let you know.

**Comment by netmilk** [comment]
Hey! I think It's a super useful feature and we totally need it, but I'm not 100% if this is the right way how to implement it.

A super quick workaround would be to use a `afterEachValidation` hook and replace the header value there.

```js
var hooks = require('hooks');

SECRET_HEADERS = ['x-my-secret-header'];

hooks.afterEachValidation(transaction, callback){
  for(var key in transaction['real']]['headers']) {
    if(SECRET_HEADERS.indexOf(key) > -1){
      transaction['real']]['headers'][key] = "***HIDDEN SECRET DATA***";
    }
  }
}
```

**Comment by realityking** [comment]
Interesting workaround, didn't think of that approach.

Out of curiosity, what downsides do you see with the approach I took?

**Comment by realityking** [comment]
I finally got around to testing @netmilk's workaround. Turns out there's no `afterEachValidation` hook but it does work with the `afterEach` hook.

My code:

```js
var hooks = require('hooks');
const SECRET_HEADERS = ['Authorization'].map(header => header.toLowerCase());

hooks.afterEach(function(transaction, done) {
  Object.keys(transaction['request']['headers']).forEach(function(key) {
    if(SECRET_HEADERS.indexOf(key.toLowerCase()) > -1){
      transaction['request']['headers'][key] = "***HIDDEN SECRET DATA***";
    }
  });

  done();
});
```

From my perspective this can now be closed. 👍

**Comment by honzajavorek** [comment]
I'm glad to hear that! Thanks for giving it a try and getting back. I think I'll create another issue anyway to add this to docs.

**Pull request closed without merging**
