### PR TITLE
Fixing the example in Ruby Hooks docs

### PR DESCRIPTION
**Pull request by netmilk**

### CODE REVIEW

**Comment by honzajavorek** [comment]
Is this some special Markdown syntax supported by Sphinx? Never seen this before in Markdown.

**Comment by w-vi** [comment]
It's an example block triple back tick watch it closely

**Comment by kylef** [comment]
@honzajavorek This is in a code-block, it's valid Ruby change. :+1: on merging, this was incorrect before.

**Comment by honzajavorek** [comment]
Ah! I get it (facepalm) I thought it's something different than it is. Thanks for clarification.

**Pull request merged**
