### PR TITLE
Support node 4 and 5 in readme

### PR DESCRIPTION
**Pull request by netmilk**

### CODE REVIEW

**Comment by w-vi** [comment]
@netmilk  it works also on iojs 2.x.x so i would update the readme thatit supports iojs too

**Comment by honzajavorek** [comment]
Sorry for hijacking the PR, but I felt like I could help.

- Addressed @w-vi's comment.
- Reworded the sentence and ordered the versions so the newest ones are mentioned first.
- Removed `~0.8.15` since we do not seem to test against it so we apparently can't guarantee Dredd will work with it.

**Comment by w-vi** [comment]
@hj can you squash it? 3 commits for changing README feel a little bit too many :)

**Comment by honzajavorek** [comment]
@w-vi rebased

**Pull request merged**
