### PR TITLE
Implement Semantic Release

### PR DESCRIPTION
**Pull request by honzajavorek**
Closes https://github.com/apiaryio/dredd/issues/438

Ignore errored/unfinished Perl build, it will be resolved by https://github.com/ungrim97/Dredd-Hooks/pull/4.

### CODE REVIEW

**Comment by JackuB** [comment]
Should https://github.com/apiaryio/dredd/blob/master/CONTRIBUTING.md be updated with required commit format for PRs?

**Comment by honzajavorek** [comment]
@JackuB It should! Good point. I'll edit it in subsequent PR.

**Comment by JackuB** [comment]
Looking good then

**Comment by honzajavorek** [comment]
@JackuB thanks!

**Pull request merged**
